# Generated by Django 5.0.3 on 2024-05-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.IntegerField()),
                ('sender', models.IntegerField()),
                ('message', models.TextField()),
                ('type_message', models.CharField(choices=[('AV', 'aviso'), ('MA', 'marcou'), ('RE', 'espondeu'), ('DM', 'deletado pela moderação')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Notificações',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('profile_name', models.CharField(max_length=100, verbose_name='Nome do Perfil')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
