# Generated by Django 5.0.3 on 2024-05-22 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='app_notification.users'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='app_notification.users'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_message',
            field=models.CharField(choices=[('AV', 'aviso'), ('MA', 'marcou'), ('RE', 'respondeu'), ('DM', 'deletado pela moderação')], max_length=2),
        ),
    ]
